# Generated by Django 5.1.4 on 2024-12-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='default_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='В процентах'),
        ),
    ]
