# Generated by Django 5.1.4 on 2024-12-18 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_game_default_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='downloads',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во скачиваний'),
        ),
        migrations.AddField(
            model_name='game',
            name='size',
            field=models.FloatField(default=0.0, verbose_name='Размер'),
        ),
    ]
