# Generated by Django 5.1.4 on 2024-12-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_game_added_at_game_downloads_game_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_price',
            field=models.PositiveIntegerField(verbose_name='Первоначальная цена'),
        ),
        migrations.AlterField(
            model_name='game',
            name='default_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена с учетом скидоса'),
        ),
    ]
