# Generated by Django 5.1.4 on 2024-12-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_game_current_price_alter_game_default_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='game',
            name='studio',
        ),
        migrations.RemoveField(
            model_name='game',
            name='tags',
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(related_name='genres', to='home.genre', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='game',
            name='studio',
            field=models.ManyToManyField(related_name='studio', to='home.studio', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='home.tags', verbose_name='Tег'),
        ),
    ]
