# Generated by Django 5.1.4 on 2024-12-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_game_description_game_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='full_description',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='game',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое Описание'),
        ),
    ]
