# Generated by Django 5.1.4 on 2024-12-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_genre_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={},
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
